### ISSUE TITLE
Python class lost its verify method

### ISSUE THREAD

**Issue by Rested** [saltedge/saltedge-examples#36]

**Comment by idanci** [comment]
@alisnic please put [it](https://github.com/saltedge/saltedge-examples/pull/34/files#diff-065db89977e742fc425bbb79461eb7fdL60) back

**Comment by Rested** [comment]
Ideally not reintroducing the pycrypto dependency!

**Comment by Rested** [comment]
Also the crypto.verify(self._public_key, base64.b64decode(signature), message, self.digest) code is wrong, since self._public_key is a `PKey` object and crypo.verify takes an `_x509` object as its first parameter.

**Comment by mtkachenk0** [comment]
@Rested Hello,
Can you please specify why is `pycrypto` bad?

**Comment by mtkachenk0** [comment]
@Rested https://github.com/saltedge/saltedge-examples/pull/37

take a look please, 
how do you find that?

**Comment by kueben** [comment]
Still not working for me.

**Comment by kueben** [comment]
Is it still {url}|{body} as the message?

**Comment by alisnic** [comment]
yep, {callback_url}|{post_body}. Can you provide more details?

**Comment by kueben** [comment]
Yes sure, do you have somewhere i can send you the data more privately?

**Comment by alisnic** [comment]
andreil.lisnic at gmail. Can you send me a signature and request that you received so that we debug the example?
