### ISSUE TITLE
PHP example lacks all the Exceptions classes

### ISSUE THREAD

**Issue by nekhbet** [saltedge/saltedge-examples#42]
You can fix it by adding: 

class InvalidArgumentException extends \Exception{};
class RuntimeException extends \Exception{};
class LogicException extends \Exception{};

**Comment by nekhbet** [comment]
You are right lol, never heard (and used) of them. I use in dev latest PHP 7 version.
The issue is that I'm using namespaces (like probably everyone nowadays) so the class names of that type need to be prefixed with "\"

**Comment by alisnic** [comment]
Glad we cleared that out!
