### ISSUE TITLE
Update docstring for saltedge.py

### ISSUE THREAD

**Issue by MatthewSBarnes** [saltedge/saltedge-examples#64]
Hey there, looking through your code examples and i noticed that your documentation seems a bit out of date, wondering if you can spend a few minutes to update it? Thanks!

https://github.com/saltedge/saltedge-examples/blob/797fc18764895961080107c8e931356f0adb0dff/python/saltedge.py#L46-L56

**Comment by alisnic** [comment]
Hi, thanks for report! Will update
