### ISSUE TITLE
This doesn't work as the usage of function is wrong. Can you please update this? 

### ISSUE THREAD

**Issue by manojvenkat** [saltedge/saltedge-examples#66]
https://github.com/saltedge/saltedge-examples/blob/c35ed53fb895590475585e047e6bf6420301ee14/python/post_request.py#L4

**Comment by alisnic** [comment]
Thanks for report! will update

**Comment by alisnic** [comment]
Sample updated

**Comment by manojvenkat** [comment]
Thanks a lot @alisnic !
