### ISSUE TITLE
Python request signing using `crpytography`

### ISSUE THREAD

**Issue by jordan-dimov** [saltedge/saltedge-examples#68]
The request signing example in this repo uses `pyOpenSSL`. On that module's page on PyPI there is a prominent warning, which reads: "Note: The Python Cryptographic Authority strongly suggests the use of pyca/cryptography where possible. If you are using pyOpenSSL for anything other than making a TLS connection you should move to cryptography and drop your pyOpenSSL dependency." 

In short, it's recommended to use `cryptography` instead of `pyOpenSSL`. 

I tried creating an analogous "pure Python" implementation for signing requests, but for some reason I don't get the same signatures (and the requests fail with a signature mismatch error). Could you point me to an example of correct `cryptography` implementation, or let me know what is wrong with the code below, which works but produces a different (rather shorter) signature:

    import hashlib, hmac, base64

    def sign(request_msg, private_key_text):
        sig = hmac.new(private_key_text.encode("utf-8"), request_msg.encode("utf-8"), hashlib.sha256)
        return base64.b64encode(sig.digest()).decode()

**Comment by alisnic** [comment]
HI @jordan-dimov, thanks for report! We will take a look at this

**Comment by alisnic** [comment]
fix was merged in https://github.com/saltedge/saltedge-examples/pull/69, @jordan-dimov please check

**Comment by jordan-dimov** [comment]
Fantastic, thank you very much @alisnic! Such a quick response.
Works like a charm.
